-- Insert price list items (master/default items)
-- These are available to all companies

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-1', 'Pre-Construction', 'Temporary toilet per month', '', 'MO', 350.00, NULL, NULL, false),
  ('pl-2', 'Pre-Construction', 'Residential Supervision / Project Management - per hour', '', 'HR', 96.82, NULL, NULL, false),
  ('pl-3', 'Pre-Construction', 'Commercial Supervision / Project Management - per hour', '', 'HR', 104.34, NULL, NULL, false),
  ('pl-4', 'Pre-Construction', 'Content Manipulation charge - per hour', '', 'HR', 80.13, NULL, NULL, false),
  ('pl-5', 'Pre-Construction', 'General Demolition - per hour', '', 'HR', 80.22, NULL, NULL, false),
  ('pl-6', 'Pre-Construction', 'Temporary fencing - 5-8 months (per month)', '', 'LF', 1.29, NULL, NULL, false),
  ('pl-7', 'Pre-Construction', 'Temporary power - hookup', '', 'EA', 2500.00, NULL, NULL, false),
  ('pl-8', 'Pre-Construction', 'Survey property building lines and elevations', '', 'EA', 3200.00, NULL, NULL, false),
  ('pl-9', 'Pre-Construction', 'General Laborer - per hour', '', 'HR', 80.13, NULL, NULL, false),
  ('pl-10', 'Pre-Construction', 'Engineering fees (Bid Item)', '', 'EA', 0, NULL, NULL, false),
  ('pl-11', 'Pre-Construction', 'Architectural/Drafting fees (Bid Item)', '', 'EA', 0, NULL, NULL, false),
  ('pl-12', 'Pre-Construction', 'Taxes, insurance, permits & fees (Bid Item)', '', 'EA', 0, NULL, NULL, false),
  ('pl-13', 'Pre-Construction', 'Erosion control - sand or gravel', '', 'CY', 250.00, NULL, NULL, false),
  ('pl-14', 'Pre-Construction', 'Lead test fee - full service lead survey - base fee', '', 'EA', 700.00, NULL, NULL, false),
  ('pl-15', 'Pre-Construction', 'Dumpster load - Approx. 40 yards, 7-8 tons of debris', '', 'EA', 1950.00, NULL, NULL, false),
  ('pl-16', 'Pre-Construction', 'Dumpster load - Approx. 30 yards, 5-7 tons of debris', '', 'EA', 1570.00, NULL, NULL, false),
  ('pl-17', 'Pre-Construction', 'Haul debris - per pickup truck load - including dump fees', '', 'EA', 270.14, NULL, NULL, false),
  ('pl-18', 'Foundation and Waterproofing', 'Excavation (Bid Item)', '', 'EA', 0, NULL, NULL, false),
  ('pl-19', 'Foundation and Waterproofing', 'Excavator and operator 6hr minimum', '', 'HR', 350.00, NULL, NULL, false),
  ('pl-20', 'Foundation and Waterproofing', 'Haul dirt per pickup truck load including dump 10 CY', '', 'EA', 550.00, NULL, NULL, false),
  ('pl-21', 'Foundation and Waterproofing', 'Steel rebar - #4 (1/2")', '', 'LF', 2.52, NULL, NULL, false),
  ('pl-22', 'Foundation and Waterproofing', 'Steel rebar - #5 (5/8")', '', 'LF', 3.44, NULL, NULL, false),
  ('pl-23', 'Foundation and Waterproofing', 'Steel rebar - j-bar - #4, 2\', '', 'EA', 6.46, NULL, NULL, false),
  ('pl-24', 'Foundation and Waterproofing', 'Steel rebar - j-bar - #4, 4\', '', 'EA', 11.36, NULL, NULL, false),
  ('pl-25', 'Foundation and Waterproofing', 'Footings - labor and materials', '', 'CY', 742.42, NULL, NULL, false),
  ('pl-26', 'Foundation and Waterproofing', 'Footings - 24" x 10"', '', 'LF', 52.06, NULL, NULL, false),
  ('pl-27', 'Foundation and Waterproofing', 'Concrete grade beam', '', 'CY', 1124.63, NULL, NULL, false),
  ('pl-28', 'Foundation and Waterproofing', 'Concrete wall - labor & materials', '', 'CY', 636.57, NULL, NULL, false),
  ('pl-29', 'Foundation and Waterproofing', 'Concrete wall - over 8\', '', 'CY', 998.20, NULL, NULL, false),
  ('pl-30', 'Foundation and Waterproofing', 'Concrete pump truck (per hour)', '', 'HR', 287.59, NULL, NULL, false),
  ('pl-31', 'Foundation and Waterproofing', 'Gravel - washed (per CY)', '', 'CY', 47.43, NULL, NULL, false),
  ('pl-32', 'Foundation and Waterproofing', 'Gravel under slab - in place', '', 'CY', 52.97, NULL, NULL, false),
  ('pl-33', 'Foundation and Waterproofing', 'Rigid foam insulation board - 2"', '', 'SF', 2.60, NULL, NULL, false),
  ('pl-34', 'Foundation and Waterproofing', 'Moisture protection before slab 6mil', '', 'SF', 72.00, NULL, NULL, false),
  ('pl-35', 'Foundation and Waterproofing', 'Concrete slab on grade - 6" - finished in place', '', 'SF', 10.52, NULL, NULL, false),
  ('pl-36', 'Foundation and Waterproofing', 'Add for fiber mesh - 4" concrete slab', '', 'SF', 0.12, NULL, NULL, false),
  ('pl-37', 'Foundation and Waterproofing', 'Add for color & stamped pattern (brick/stone) in slab', '', 'SF', 10.76, NULL, NULL, false),
  ('pl-38', 'Foundation and Waterproofing', 'Concrete slab on grade - 4" - finished in place', '', 'SF', 8.68, NULL, NULL, false),
  ('pl-39', 'Foundation and Waterproofing', 'Concrete finisher - per hour minimum 6hrs', '', 'HR', 182.32, NULL, NULL, false),
  ('pl-40', 'Foundation and Waterproofing', 'Waterproofing - sheet membrane', '', 'SF', 5.70, NULL, NULL, false),
  ('pl-41', 'Foundation and Waterproofing', 'Waterproofing - Drainage mat', '', 'SF', 8.85, NULL, NULL, false),
  ('pl-42', 'Foundation and Waterproofing', 'Waterproof concrete & masonry paint', '', 'SF', 2.04, NULL, NULL, false),
  ('pl-43', 'Storm drainage & footing drainage', 'Gravel - washed for footing drainage', '', 'CY', 250.00, NULL, NULL, false),
  ('pl-44', 'Storm drainage & footing drainage', 'Drain/Vent line - PVC pipe with fitting and hanger, 4"', '', 'LF', 38.63, NULL, NULL, false),
  ('pl-45', 'Storm drainage & footing drainage', 'Foundation drainage system - French drain & drainage mat', '', 'LF', 50.00, NULL, NULL, false),
  ('pl-46', 'Storm drainage & footing drainage', 'Backfill foundations', '', 'HR', 350.00, NULL, NULL, false),
  ('pl-47', 'Storm drainage & footing drainage', 'Backhoe loader and operator', '', 'HR', 350.00, NULL, NULL, false),
  ('pl-48', 'Lumber and hardware material', 'Carpenter - General framer - per hour minimum 6hrs', '', 'HR', 114.86, NULL, NULL, false),
  ('pl-49', 'Lumber and hardware material', 'Timber post, 6x6', '', 'LF', 34.59, NULL, NULL, false),
  ('pl-50', 'Lumber and hardware material', '6" x 6" x 12\', '', 'EA', 95.24, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-51', 'Lumber and hardware material', '6" x 6" x 10\', '', 'EA', 79.05, NULL, NULL, false),
  ('pl-52', 'Lumber and hardware material', 'Beam - engineered strand lumber - 5 1/4" x 11 7/8"', '', 'LF', 39.58, NULL, NULL, false),
  ('pl-53', 'Lumber and hardware material', 'Beam - engineered strand lumber - 5 1/4" x 9 1/2"', '', 'LF', 35.28, NULL, NULL, false),
  ('pl-54', 'Lumber and hardware material', 'Beam - engineered strand lumber - 3 1/2" x 7 1/4"', '', 'LF', 27.20, NULL, NULL, false),
  ('pl-55', 'Lumber and hardware material', '1-3/4" x 11-7/8" LVL lumber - material only', '', 'LF', 12.10, NULL, NULL, false),
  ('pl-56', 'Lumber and hardware material', '2" x 12" x 12\', '', 'EA', 36.51, NULL, NULL, false),
  ('pl-57', 'Lumber and hardware material', '2" x 12" x 16\', '', 'EA', 36.87, NULL, NULL, false),
  ('pl-58', 'Lumber and hardware material', '2" x 12" x 14\', '', 'EA', 32.72, NULL, NULL, false),
  ('pl-59', 'Lumber and hardware material', 'I-joist - 12" deep - 2 5/16" flange', '', 'LF', 7.27, NULL, NULL, false),
  ('pl-60', 'Lumber and hardware material', 'I-joist - 12" deep - 1 3/4" flange', '', 'LF', 6.55, NULL, NULL, false),
  ('pl-61', 'Lumber and hardware material', 'Rim joist - engineered LVL - 1-5/16" x 11-7/8"', '', 'LF', 6.31, NULL, NULL, false),
  ('pl-62', 'Lumber and hardware material', '1-3/4" x 9-1/2" LVL lumber - material only', '', 'LF', 10.59, NULL, NULL, false),
  ('pl-63', 'Lumber and hardware material', 'Framing strap - 24" long', '', 'EA', 48.02, NULL, NULL, false),
  ('pl-64', 'Lumber and hardware material', 'Framing strap - 66" long', '', 'EA', 94.94, NULL, NULL, false),
  ('pl-65', 'Lumber and hardware material', 'Framing hold down - 16"', '', 'EA', 164.25, NULL, NULL, false),
  ('pl-66', 'Lumber and hardware material', 'Concrete hold down strap', '', 'EA', 41.30, NULL, NULL, false),
  ('pl-67', 'Lumber and hardware material', 'Framing/truss hurricane strap', '', 'EA', 17.91, NULL, NULL, false),
  ('pl-68', 'Lumber and hardware material', 'Framing hurricane tie', '', 'EA', 14.78, NULL, NULL, false),
  ('pl-69', 'Lumber and hardware material', 'Framing hanger - 2" x 10" or 2" x 12"', '', 'EA', 21.38, NULL, NULL, false),
  ('pl-70', 'Lumber and hardware material', 'Framing hanger - 2" x 6" or 2" x 8"', '', 'EA', 19.24, NULL, NULL, false),
  ('pl-71', 'Lumber and hardware material', 'Sheathing - OSB - 3/4"- T&G - High grade eng. wtr resist.', '', 'SF', 4.00, NULL, NULL, false),
  ('pl-72', 'Lumber and hardware material', '2" x 6" x 10\', '', 'EA', 8.67, NULL, NULL, false),
  ('pl-73', 'Lumber and hardware material', '2" x 6" x 8\', '', 'EA', 6.94, NULL, NULL, false),
  ('pl-74', 'Lumber and hardware material', '2" x 6" x 12\', '', 'EA', 10.45, NULL, NULL, false),
  ('pl-75', 'Lumber and hardware material', '2" x 4" x 92 5/8" pre-cut stud (for 8\', '', 'EA', 4.94, NULL, NULL, false),
  ('pl-76', 'Lumber and hardware material', '2" x 6" x 20\', '', 'EA', 30.68, NULL, NULL, false),
  ('pl-77', 'Lumber and hardware material', '2" x 6" x 20\', '', 'EA', 19.70, NULL, NULL, false),
  ('pl-78', 'Lumber and hardware material', 'Sheathing - plywood - 1/2" CDX', '', 'SF', 3.85, NULL, NULL, false),
  ('pl-79', 'Lumber and hardware material', '2" x 4" x 10\', '', 'EA', 6.37, NULL, NULL, false),
  ('pl-80', 'Lumber and hardware material', '2" x 4" x 20\', '', 'EA', 14.51, NULL, NULL, false),
  ('pl-81', 'Lumber and hardware material', '2" x 4" x 20\', '', 'EA', 20.16, NULL, NULL, false),
  ('pl-82', 'Lumber and hardware material', 'Truss - 4/12 slope', '', 'LF', 5.40, NULL, NULL, false),
  ('pl-83', 'Lumber and hardware material', 'Truss - 6/12 slope', '', 'LF', 5.77, NULL, NULL, false),
  ('pl-84', 'Lumber and hardware material', 'Truss - 8/12 slope', '', 'LF', 5.83, NULL, NULL, false),
  ('pl-85', 'Lumber and hardware material', 'Truss - 12/12 slope', '', 'LF', 7.71, NULL, NULL, false),
  ('pl-86', 'Lumber and hardware material', 'Fascia - 1" x 8" - #2 pine', '', 'LF', 13.85, NULL, NULL, false),
  ('pl-87', 'Lumber and hardware material', 'Sheathing - OSB - 1/2"', '', 'SF', 3.69, NULL, NULL, false),
  ('pl-88', 'Lumber and hardware material', 'Telehandler/forklift (per week) - no operator', '', 'WK', 1220.00, NULL, NULL, false),
  ('pl-89', 'Lumber and hardware material', 'Crane and operator - 30 ton capacity', '', 'HR', 240.00, NULL, NULL, false),
  ('pl-90', 'Frame Labor only', 'Labor to frame house per sf', '', 'SF', 19.69, NULL, NULL, false),
  ('pl-91', 'Frame Labor only', 'Carpenter - General Framer - per hour', '', 'HR', 114.86, NULL, NULL, false),
  ('pl-92', 'Frame Labor only', 'General Laborer - per hour', '', 'HR', 80.13, NULL, NULL, false),
  ('pl-93', 'Frame Labor only', 'General Demolition - per hour', '', 'HR', 80.22, NULL, NULL, false),
  ('pl-94', 'Roof material & labor', 'Roofer - per hour', '', 'HR', 259.28, NULL, NULL, false),
  ('pl-95', 'Roof material & labor', 'Tear off, haul and dispose of comp. shingles - Laminated', '', 'SQ', 116.73, NULL, NULL, false),
  ('pl-96', 'Roof material & labor', 'Drip edge', '', 'LF', 4.46, NULL, NULL, false),
  ('pl-97', 'Roof material & labor', 'Drip edge/gutter apron', '', 'LF', 4.73, NULL, NULL, false),
  ('pl-98', 'Roof material & labor', 'Roof vent - turtle type - Metal', '', 'EA', 112.95, NULL, NULL, false),
  ('pl-99', 'Roof material & labor', 'Flashing - pipe jack', '', 'EA', 83.08, NULL, NULL, false),
  ('pl-100', 'Roof material & labor', 'Skylight - flat fixed, up to 6 sf', '', 'EA', 761.56, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-101', 'Roof material & labor', 'Skylight - flat fixed, 9.1 - 10 sf', '', 'EA', 947.68, NULL, NULL, false),
  ('pl-102', 'Roof material & labor', 'Skylight flashing kit - dome', '', 'EA', 126.43, NULL, NULL, false),
  ('pl-103', 'Roof material & labor', 'Chimney flashing - large (32" x 60")', '', 'EA', 996.10, NULL, NULL, false),
  ('pl-104', 'Roof material & labor', 'Valley metal - (W) profile', '', 'LF', 10.71, NULL, NULL, false),
  ('pl-105', 'Roof material & labor', 'Step flashing', '', 'LF', 18.89, NULL, NULL, false),
  ('pl-106', 'Roof material & labor', 'Cap flashing', '', 'LF', 29.69, NULL, NULL, false),
  ('pl-107', 'Roof material & labor', 'Ice & water barrier', '', 'SF', 2.87, NULL, NULL, false),
  ('pl-108', 'Roof material & labor', 'Roofing felt - synthetic underlayment', '', 'SQ', 77.98, NULL, NULL, false),
  ('pl-109', 'Roof material & labor', 'Roofing felt - 30 lb.', '', 'SQ', 72.87, NULL, NULL, false),
  ('pl-110', 'Roof material & labor', 'Laminated 30yr comp. shingle - w/felt', '', 'SQ', 720.00, NULL, NULL, false),
  ('pl-111', 'Roof material & labor', 'Laminated - Shake look Premium grd comp. shingle - w/felt', '', 'SQ', 950.00, NULL, NULL, false),
  ('pl-112', 'Roof material & labor', 'Continuous ridge vent - shingle-over style', '', 'LF', 16.41, NULL, NULL, false),
  ('pl-113', 'Roof material & labor', 'Hip / Ridge cap - High profile - composition shingles', '', 'LF', 10.80, NULL, NULL, false),
  ('pl-114', 'Roof material & labor', 'TPO/PVC roofing - 60mil', '', 'SQ', 1004.35, NULL, NULL, false),
  ('pl-115', 'Roof material & labor', 'Membrane Roofing Installer - per hour', '', 'HR', 138.07, NULL, NULL, false),
  ('pl-116', 'Roof material & labor', 'Tile roofing - Clay - "S" or flat tile', '', 'SQ', 1150.90, NULL, NULL, false),
  ('pl-117', 'Roof material & labor', 'Metal roofing - High grade', '', 'SF', 18.79, NULL, NULL, false),
  ('pl-118', 'Windows and exterior doors', 'Window Installer - per hour', '', 'HR', 123.21, NULL, NULL, false),
  ('pl-119', 'Windows and exterior doors', 'Main exterior door average grade', '', 'EA', 2137.94, NULL, NULL, false),
  ('pl-120', 'Windows and exterior doors', 'Main exterior door - fiberglass / wood w/detail - 5\', '', 'EA', 4337.94, NULL, NULL, false),
  ('pl-121', 'Windows and exterior doors', 'French double doors - Exterior - pre-hung unit', '', 'EA', 3200.00, NULL, NULL, false),
  ('pl-122', 'Windows and exterior doors', 'Vinyl window, picture/fixed, average grade', '', 'EA', 845.09, NULL, NULL, false),
  ('pl-123', 'Windows and exterior doors', 'Vinyl sliding window - average grade', '', 'EA', 675.08, NULL, NULL, false),
  ('pl-124', 'Windows and exterior doors', 'Aluminum window, single hung 13-19 sf (2 pane w/thermal)', '', 'EA', 592.13, NULL, NULL, false),
  ('pl-125', 'Windows and exterior doors', '6-0 6-8 vinyl sliding patio door', '', 'EA', 1285.07, NULL, NULL, false),
  ('pl-126', 'Windows and exterior doors', 'Bifold door - exterior glass', '', 'EA', 16849.22, NULL, NULL, false),
  ('pl-127', 'Windows and exterior doors', 'Garage door average grade 8\', '', 'EA', 6500.00, NULL, NULL, false),
  ('pl-128', 'Windows and exterior doors', 'Overhead (garage) door opener - Premium grade', '', 'EA', 630.88, NULL, NULL, false),
  ('pl-129', 'Windows and exterior doors', 'Garage door & hardware - 10\', '', 'EA', 4862.59, NULL, NULL, false),
  ('pl-130', 'Siding', 'Siding Installer - per hour', '', 'HR', 186.32, NULL, NULL, false),
  ('pl-131', 'Siding', 'Flashing tape - self-adhesive', '', 'LF', 1.78, NULL, NULL, false),
  ('pl-132', 'Siding', 'Metal Z flashing top of windows/bellyband', '', 'LF', 4.04, NULL, NULL, false),
  ('pl-133', 'Siding', 'House wrap (air/moisture barrier)', '', 'SF', 65.00, NULL, NULL, false),
  ('pl-134', 'Siding', 'Rain screen system with 1" x 3" furring strips', '', 'SF', 2.89, NULL, NULL, false),
  ('pl-135', 'Siding', 'Fascia - 1" x 4" - #1 pine', '', 'LF', 11.07, NULL, NULL, false),
  ('pl-136', 'Siding', 'Fascia - 1" x 6" - #1 pine', '', 'LF', 12.91, NULL, NULL, false),
  ('pl-137', 'Siding', 'Fascia - 1" x 8" - #2 pine', '', 'LF', 13.85, NULL, NULL, false),
  ('pl-138', 'Siding', 'Fascia - 1" x 8" - #3 cedar', '', 'LF', 16.42, NULL, NULL, false),
  ('pl-139', 'Siding', 'Fiber cement lap siding - 8"', '', 'SF', 8.17, NULL, NULL, false),
  ('pl-140', 'Siding', 'Fiber cement lap siding - 6"', '', 'SF', 8.79, NULL, NULL, false),
  ('pl-141', 'Siding', 'Siding - beveled - cedar', '', 'SF', 13.46, NULL, NULL, false),
  ('pl-142', 'Siding', 'Siding- fiber cement panel type', '', 'SF', 8.19, NULL, NULL, false),
  ('pl-143', 'Siding', 'Siding - fiber cement - shingle type panel', '', 'SF', 13.63, NULL, NULL, false),
  ('pl-144', 'Siding', 'Siding - cedar shingle', '', 'SF', 17.08, NULL, NULL, false),
  ('pl-145', 'Siding', 'Soffit - fiber cement panel', '', 'SF', 10.95, NULL, NULL, false),
  ('pl-146', 'Siding', 'Siding - vinyl', '', 'SF', 8.81, NULL, NULL, false),
  ('pl-147', 'Siding', 'Siding - aluminum (.024 thickness)', '', 'SF', 11.43, NULL, NULL, false),
  ('pl-148', 'Siding', 'Pine or equal T&G', '', 'SF', 9.31, NULL, NULL, false),
  ('pl-149', 'Plumbing', 'Plumber - per hour', '', 'HR', 292.42, NULL, NULL, false),
  ('pl-150', 'Plumbing', 'Rough-in plumbing - per fixture PEX', '', 'EA', 1541.55, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-151', 'Plumbing', 'Shower base fiberglass', '', 'EA', 905.64, NULL, NULL, false),
  ('pl-152', 'Plumbing', 'Bathtub fiberglass', '', 'EA', 1642.07, NULL, NULL, false),
  ('pl-153', 'Plumbing', 'Exterior faucet / hose bibb', '', 'EA', 190.72, NULL, NULL, false),
  ('pl-154', 'Plumbing', 'Refrigerator/icemaker water supply box with valve', '', 'EA', 274.38, NULL, NULL, false),
  ('pl-155', 'Plumbing', 'Toilet average grade', '', 'EA', 870.96, NULL, NULL, false),
  ('pl-156', 'Plumbing', 'Tub/shower faucet', '', 'EA', 619.07, NULL, NULL, false),
  ('pl-157', 'Plumbing', 'Sink faucet -vanity', '', 'EA', 431.06, NULL, NULL, false),
  ('pl-158', 'Plumbing', 'Sink faucet - Kitchen - High grade', '', 'EA', 559.06, NULL, NULL, false),
  ('pl-159', 'Plumbing', 'Water heater - 50 gallon - Gas - 6 yr', '', 'EA', 1973.09, NULL, NULL, false),
  ('pl-160', 'Plumbing', 'Water heater - 6 gallon - Electric', '', 'EA', 1401.83, NULL, NULL, false),
  ('pl-161', 'Plumbing', 'Water heater - tankless - 15kw to 20kw - Electric', '', 'EA', 2319.99, NULL, NULL, false),
  ('pl-162', 'Plumbing', 'Water heater - tankless - 5-5.9 gallon - Gas - Power vent', '', 'EA', 3269.45, NULL, NULL, false),
  ('pl-163', 'Plumbing', 'Thermal expansion tank - 2 gallon', '', 'EA', 672.63, NULL, NULL, false),
  ('pl-164', 'Fire sprinklers', 'Concealed fire sprinkler system (SF) - Residential', '', 'SF', 7.00, NULL, NULL, false),
  ('pl-165', 'Fire sprinklers', 'Concealed fire sprinkler system (SF of bldg) Comercial', '', 'SF', 10.00, NULL, NULL, false),
  ('pl-166', 'Fire Alarm', 'Fire alarm Monitoring system Comercial( per Bldg sf)', '', 'SF', 13.00, NULL, NULL, false),
  ('pl-167', 'Fire Alarm', 'Circulation pump - 10 gpm', '', 'EA', 2480.28, NULL, NULL, false),
  ('pl-168', 'Mechanical/HVAC', 'HVAC Technician - per hour', '', 'HR', 211.77, NULL, NULL, false),
  ('pl-169', 'Mechanical/HVAC', 'Heating and cooling unit - 5 ton, 140 MBH', '', 'EA', 14579.68, NULL, NULL, false),
  ('pl-170', 'Mechanical/HVAC', 'Ductwork system - hot or cold air - 2200 to 2500 SF home', '', 'EA', 11535.61, NULL, NULL, false),
  ('pl-171', 'Mechanical/HVAC', 'Exhaust fan', '', 'EA', 558.02, NULL, NULL, false),
  ('pl-172', 'Mechanical/HVAC', 'Ductwork - flexible - insulated - 6" round', '', 'LF', 14.54, NULL, NULL, false),
  ('pl-173', 'Mechanical/HVAC', 'Duct-free split system - 2 zone - High efficiency', '', 'EA', 4378.48, NULL, NULL, false),
  ('pl-174', 'Mechanical/HVAC', 'Ductwork system - hot and cold air (per run)', '', 'EA', 667.18, NULL, NULL, false),
  ('pl-175', 'Mechanical/HVAC', 'Reversible cycle heat pump - packaged unit - 3 ton 14 SEER', '', 'EA', 5388.27, NULL, NULL, false),
  ('pl-176', 'Mechanical/HVAC', 'Heat pump - exterior coil unit - 5 ton - 15-16 SEER', '', 'EA', 4551.73, NULL, NULL, false),
  ('pl-177', 'Mechanical/HVAC', 'Duct-free split system - 4 zone - High efficiency', '', 'EA', 6413.91, NULL, NULL, false),
  ('pl-178', 'Mechanical/HVAC', 'Condenser pad - 36" x 36"', '', 'EA', 102.32, NULL, NULL, false),
  ('pl-179', 'Electrical', 'Electrician - per hour minimum 6 hours', '', 'HR', 182.98, NULL, NULL, false),
  ('pl-180', 'Electrical', 'Meter base and main disconnect - 200 amp', '', 'EA', 1500.00, NULL, NULL, false),
  ('pl-181', 'Electrical', 'Breaker panel - 200 amp w/arc fault breakers', '', 'EA', 3324.78, NULL, NULL, false),
  ('pl-182', 'Electrical', 'Rewire\\wire - avg. residence - boxes & wiring', '', 'SF', 7.20, NULL, NULL, false),
  ('pl-183', 'Electrical', 'Circuit breaker - arc-fault circuit-interrupter (AFCI)', '', 'EA', 129.56, NULL, NULL, false),
  ('pl-184', 'Electrical', 'Ground fault interrupter (GFI) outlet - tamper resistant', '', 'EA', 63.02, NULL, NULL, false),
  ('pl-185', 'Electrical', 'Outlet Replace', '', 'EA', 68.91, NULL, NULL, false),
  ('pl-186', 'Electrical', 'Switch', '', 'EA', 63.91, NULL, NULL, false),
  ('pl-187', 'Electrical', 'Switch - 3 way', '', 'EA', 73.91, NULL, NULL, false),
  ('pl-188', 'Electrical', 'Dimmer switch', '', 'EA', 83.91, NULL, NULL, false),
  ('pl-189', 'Insulation', 'General Demolition - per hour', '', 'HR', 80.22, NULL, NULL, false),
  ('pl-190', 'Insulation', 'Insulation Installer - per hour', '', 'HR', 101.56, NULL, NULL, false),
  ('pl-191', 'Insulation', 'Moisture protection for crawl space - visqueen - 10 mil', '', 'SF', 0.70, NULL, NULL, false),
  ('pl-192', 'Insulation', 'Batt insulation - 12" - R38', '', 'SF', 2.96, NULL, NULL, false),
  ('pl-193', 'Insulation', 'Batt insulation - 6" - R21 - paper / foil faced', '', 'SF', 2.07, NULL, NULL, false),
  ('pl-194', 'Insulation', 'Sprayed polyurethane foam - 2lb mix - per inch thick', '', 'SF', 1.62, NULL, NULL, false),
  ('pl-195', 'Insulation', 'Blown-in insulation - 20" depth - R50', '', 'SF', 3.14, NULL, NULL, false),
  ('pl-196', 'Insulation', 'Rigid foam insulation board - 2"', '', 'SF', 3.16, NULL, NULL, false),
  ('pl-197', 'Drywall', 'Drywall installer/finisher - per hour minimum 6hrs', '', 'HR', 163.78, NULL, NULL, false),
  ('pl-198', 'Drywall', '5/8" drywall - hung, taped, floated, ready for paint', '', 'SF', 4.46, NULL, NULL, false),
  ('pl-199', 'Drywall', '5/8" drywall - hung, taped, ready for texture install only(not material)', '', 'SF', 3.06, NULL, NULL, false),
  ('pl-200', 'Drywall', '5/8" drywall - hung, taped, ready for texture', '', 'SF', 3.92, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-201', 'Drywall', '5/8" drywall - hung & fire taped only', '', 'SF', 4.21, NULL, NULL, false),
  ('pl-202', 'Drywall', '5/8" - drywall per LF - up to 4\', '', 'LF', 31.58, NULL, NULL, false),
  ('pl-203', 'Drywall', 'Seal  w/PVA primer - one coat', '', 'SF', 0.83, NULL, NULL, false),
  ('pl-204', 'Drywall', 'Texture drywall - machine', '', 'SF', 1.16, NULL, NULL, false),
  ('pl-205', 'Flooring & Carpet & Tile', 'Floor leveling cement - Average', '', 'SF', 4.68, NULL, NULL, false),
  ('pl-206', 'Flooring & Carpet & Tile', 'Flooring Installer - per hour', '', 'HR', 117.30, NULL, NULL, false),
  ('pl-207', 'Flooring & Carpet & Tile', 'Vinyl plank flooring average grade', '', 'SF', 9.75, NULL, NULL, false),
  ('pl-208', 'Flooring & Carpet & Tile', 'Vinyl plank flooring high grade', '', 'SF', 13.40, NULL, NULL, false),
  ('pl-209', 'Flooring & Carpet & Tile', 'Snaplock Laminate - simulated wood flooring', '', 'SF', 9.61, NULL, NULL, false),
  ('pl-210', 'Flooring & Carpet & Tile', 'Pre-finished solid wood flooring - High grade', '', 'SF', 18.03, NULL, NULL, false),
  ('pl-211', 'Flooring & Carpet & Tile', 'Oak flooring - #1 common - no finish', '', 'SF', 16.00, NULL, NULL, false),
  ('pl-212', 'Flooring & Carpet & Tile', 'Sand, stain, and finish wood floor', '', 'SF', 6.24, NULL, NULL, false),
  ('pl-213', 'Flooring & Carpet & Tile', 'Cherry floor - #1 or better - select grade - no finish', '', 'SF', 16.40, NULL, NULL, false),
  ('pl-214', 'Flooring & Carpet & Tile', 'Carpet Installer - per hour', '', 'HR', 117.30, NULL, NULL, false),
  ('pl-215', 'Flooring & Carpet & Tile', 'Carpet pad - High grade', '', 'SF', 1.86, NULL, NULL, false),
  ('pl-216', 'Flooring & Carpet & Tile', 'Carpet pad average grade', '', 'SF', 0.98, NULL, NULL, false),
  ('pl-217', 'Flooring & Carpet & Tile', 'Carpet standard grade', '', 'SF', 4.66, NULL, NULL, false),
  ('pl-218', 'Flooring & Carpet & Tile', 'Carpet - High grade', '', 'SF', 6.76, NULL, NULL, false),
  ('pl-219', 'Flooring & Carpet & Tile', 'Carpet - Premium grade', '', 'SF', 8.09, NULL, NULL, false),
  ('pl-220', 'Flooring & Carpet & Tile', 'Stair nosing per LF', '', 'LF', 60.68, NULL, NULL, false),
  ('pl-221', 'Flooring & Carpet & Tile', 'Mortar bed for tile', '', 'SF', 19.76, NULL, NULL, false),
  ('pl-222', 'Flooring & Carpet & Tile', '1/4" Cement board', '', 'SF', 9.80, NULL, NULL, false),
  ('pl-223', 'Flooring & Carpet & Tile', 'Ceramic/porcelain tile', '', 'SF', 38.13, NULL, NULL, false),
  ('pl-224', 'Flooring & Carpet & Tile', 'Tile floor average grade', '', 'SF', 32.83, NULL, NULL, false),
  ('pl-225', 'Interior Doors', 'Door Installer/Finish Carpenter - per hour', '', 'HR', 120.00, NULL, NULL, false),
  ('pl-226', 'Interior Doors', 'Carpenter - Finish, Trim / Cabinet - per hour', '', 'HR', 118.52, NULL, NULL, false),
  ('pl-227', 'Interior Doors', 'Interior door 6\', '', 'EA', 370.00, NULL, NULL, false),
  ('pl-228', 'Interior Doors', 'Interior door unit solid 6\', '', 'EA', 603.19, NULL, NULL, false),
  ('pl-229', 'Interior Doors', 'Interior door unit 8\', '', 'EA', 544.39, NULL, NULL, false),
  ('pl-230', 'Interior Doors', 'Interior door 8\', '', 'EA', 713.19, NULL, NULL, false),
  ('pl-231', 'Interior Doors', 'Paint door slab only - 2 coats (per side)', '', 'EA', 53.34, NULL, NULL, false),
  ('pl-232', 'Interior Doors', 'Window trim set (casing & stop)', '', 'LF', 8.97, NULL, NULL, false),
  ('pl-233', 'Interior Doors', 'Casing - 3 1/4" stain grade', '', 'LF', 4.84, NULL, NULL, false),
  ('pl-234', 'Mill/Trim Work', 'Carpenter - Finish, Trim / Cabinet - per hour', '', 'HR', 118.52, NULL, NULL, false),
  ('pl-235', 'Mill/Trim Work', 'Baseboard - 3 1/4"', '', 'LF', 5.09, NULL, NULL, false),
  ('pl-236', 'Mill/Trim Work', 'Baseboard - 5 1/4"', '', 'LF', 6.40, NULL, NULL, false),
  ('pl-237', 'Mill/Trim Work', 'Baseboard - 5 1/4" MDF - flat profile', '', 'LF', 5.56, NULL, NULL, false),
  ('pl-238', 'Mill/Trim Work', 'Baseboard - 4 1/4" MDF - w/profile', '', 'LF', 5.59, NULL, NULL, false),
  ('pl-239', 'Mill/Trim Work', 'Baseboard - 7 1/4"', '', 'LF', 8.60, NULL, NULL, false),
  ('pl-240', 'Mill/Trim Work', 'Finish Carpenter - per hour', '', 'HR', 117.84, NULL, NULL, false),
  ('pl-241', 'Mill/Trim Work', 'Casing - 2 1/4" MDF', '', 'LF', 3.63, NULL, NULL, false),
  ('pl-242', 'Mill/Trim Work', 'Crown molding - 5 1/4"', '', 'LF', 9.09, NULL, NULL, false),
  ('pl-243', 'Mill/Trim Work', 'Trim board - 1/2" x 6" - installed (pine)', '', 'LF', 5.73, NULL, NULL, false),
  ('pl-244', 'Mill/Trim Work', 'Window sill', '', 'LF', 4.44, NULL, NULL, false),
  ('pl-245', 'Mill/Trim Work', 'Stair Skirt/Apron - wall side - paint grade', '', 'LF', 25.06, NULL, NULL, false),
  ('pl-246', 'Mill/Trim Work', 'Handrail - prem. grade ornamental - hardwood - wall mount.', '', 'LF', 48.84, NULL, NULL, false),
  ('pl-247', 'Mill/Trim Work', 'Chair rail - oversized - 3 1/4"', '', 'LF', 5.43, NULL, NULL, false),
  ('pl-248', 'Mill/Trim Work', 'Crown molding - 6 1/8" to 7" MDF', '', 'LF', 9.80, NULL, NULL, false),
  ('pl-249', 'Painting', 'Painter - per hour', '', 'HR', 99.12, NULL, NULL, false),
  ('pl-250', 'Painting', 'Exterior - paint two coats', '', 'SF', 2.50, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-251', 'Painting', 'Paint the surface area - two coats', '', 'SF', 1.38, NULL, NULL, false),
  ('pl-252', 'Painting', 'Paint baseboard - two coats', '', 'LF', 2.08, NULL, NULL, false),
  ('pl-253', 'Painting', 'Paint door/window trim & jamb - Large - 2 coats (per side)', '', 'EA', 53.00, NULL, NULL, false),
  ('pl-254', 'Painting', 'Paint door slab only - 2 coats (per side)', '', 'EA', 53.34, NULL, NULL, false),
  ('pl-255', 'Painting', 'Seal & paint cabinetry - upper - inside and out', '', 'LF', 55.65, NULL, NULL, false),
  ('pl-256', 'Kitchen', 'General Demolition - per hour', '', 'HR', 80.22, NULL, NULL, false),
  ('pl-257', 'Kitchen', 'Finish Carpenter - per hour', '', 'HR', 118.52, NULL, NULL, false),
  ('pl-258', 'Kitchen', 'Cabinetry semicustom average grade', '', 'LF', 320.00, NULL, NULL, false),
  ('pl-259', 'Kitchen', 'Cabinetry - Premium grade', '', 'LF', 501.83, NULL, NULL, false),
  ('pl-260', 'Kitchen', 'Countertop - solid surface 2cm', '', 'SF', 74.88, NULL, NULL, false),
  ('pl-261', 'Kitchen', 'Countertop - quartz up to level 4 3cm', '', 'SF', 97.57, NULL, NULL, false),
  ('pl-262', 'Kitchen', 'Countertop - concrete', '', 'SF', 128.94, NULL, NULL, false),
  ('pl-263', 'Kitchen', 'Countertop - flat laid plastic laminate', '', 'LF', 52.18, NULL, NULL, false),
  ('pl-264', 'Kitchen', 'Countertop - wood - butcher block (hardrock maple)', '', 'SF', 86.68, NULL, NULL, false),
  ('pl-265', 'Kitchen', 'Cabinet knob or pull - High grade', '', 'EA', 14.90, NULL, NULL, false),
  ('pl-266', 'Kitchen', 'Sink - double basin farm style', '', 'EA', 1200.00, NULL, NULL, false),
  ('pl-267', 'Kitchen', 'Kitchen sink average grade', '', 'EA', 950.00, NULL, NULL, false),
  ('pl-268', 'Kitchen', 'Kitchen Sink - single basin', '', 'EA', 514.51, NULL, NULL, false),
  ('pl-269', 'Kitchen', 'P-trap assembly', '', 'EA', 150.14, NULL, NULL, false),
  ('pl-270', 'Kitchen', 'Plumbing fixture supply line', '', 'EA', 42.68, NULL, NULL, false),
  ('pl-271', 'Kitchen', 'Garbage disposal / disposer', '', 'EA', 442.27, NULL, NULL, false),
  ('pl-272', 'Kitchen', 'Electrician - per hour', '', 'HR', 182.98, NULL, NULL, false),
  ('pl-273', 'Kitchen', 'Recessed light fixture', '', 'EA', 201.81, NULL, NULL, false),
  ('pl-274', 'Kitchen', 'Cabinet light valance', '', 'LF', 47.24, NULL, NULL, false),
  ('pl-275', 'Kitchen', 'Pot filler faucet', '', 'EA', 622.24, NULL, NULL, false),
  ('pl-276', 'Kitchen', 'Plumber - per hour', '', 'HR', 292.42, NULL, NULL, false),
  ('pl-277', 'Bathroom', 'Vanity', '', 'LF', 363.29, NULL, NULL, false),
  ('pl-278', 'Bathroom', 'Vanity high grade', '', 'LF', 525.60, NULL, NULL, false),
  ('pl-279', 'Bathroom', 'Shower door glass average grade', '', 'EA', 1382.46, NULL, NULL, false),
  ('pl-280', 'Bathroom', 'Towel ring', '', 'EA', 49.53, NULL, NULL, false),
  ('pl-281', 'Bathroom', 'Tile - towel bar', '', 'EA', 88.60, NULL, NULL, false),
  ('pl-282', 'Bathroom', 'Toilet paper holder', '', 'EA', 64.81, NULL, NULL, false),
  ('pl-283', 'Bathroom', 'Mirror', '', 'SF', 45.49, NULL, NULL, false),
  ('pl-284', 'Bathroom', 'Bathroom mirror - w/metal frame - surface mtd LED', '', 'SF', 63.20, NULL, NULL, false),
  ('pl-285', 'Appliances', 'Built-in oven - High grade', '', 'EA', 1533.53, NULL, NULL, false),
  ('pl-286', 'Appliances', 'Range hood', '', 'EA', 1222.27, NULL, NULL, false),
  ('pl-287', 'Appliances', 'Built-in double oven - High grade', '', 'EA', 3196.40, NULL, NULL, false),
  ('pl-288', 'Appliances', 'Range - slide in - gas - High grade', '', 'EA', 2176.46, NULL, NULL, false),
  ('pl-289', 'Deck and Exterior Railing', 'Carpenter - General Framer - per hour', '', 'HR', 114.86, NULL, NULL, false),
  ('pl-290', 'Deck and Exterior Railing', 'Deck pier or footing', '', 'CY', 258.30, NULL, NULL, false),
  ('pl-291', 'Deck and Exterior Railing', 'Deck planking - hardwood (Ipe) - 1"x 6"', '', 'SF', 28.21, NULL, NULL, false),
  ('pl-292', 'Deck and Exterior Railing', 'Deck planking - Vinyl (per SF)', '', 'SF', 16.42, NULL, NULL, false),
  ('pl-293', 'Deck and Exterior Railing', 'Deck planking - 5/4" cedar (per SF)', '', 'SF', 21.32, NULL, NULL, false),
  ('pl-294', 'Deck and Exterior Railing', '4" wood polymer decking - Labor only (per SF)', '', 'SF', 13.05, NULL, NULL, false),
  ('pl-295', 'Deck and Exterior Railing', 'Deck guard rail - Vinyl average', '', 'LF', 81.40, NULL, NULL, false),
  ('pl-296', 'Tree Removals', 'Tree - removal - 12" to 24" diameter / large canopy', '', 'EA', 2159.74, NULL, NULL, false),
  ('pl-297', 'Tree Removals', 'Tree - removal - 24" to 36" diameter / large canopy', '', 'EA', 4238.32, NULL, NULL, false),
  ('pl-298', 'Tree Removals', 'Tree - removal and disposal - per hour including equipment', '', 'HR', 180.00, NULL, NULL, false),
  ('pl-299', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Paver brick', '', 'SF', 20.73, NULL, NULL, false),
  ('pl-300', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Paver brick - High grade', '', 'SF', 21.55, NULL, NULL, false);

INSERT INTO price_list_items (id, category, name, description, unit, unit_price, labor_cost, material_cost, is_custom) VALUES
  ('pl-301', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Bedding sand', '', 'CY', 60.00, NULL, NULL, false),
  ('pl-302', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Gravel under slab - in place', '', 'CY', 65.00, NULL, NULL, false),
  ('pl-303', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'General Laborer - per hour', '', 'HR', 135.00, NULL, NULL, false),
  ('pl-304', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Concrete CY - Minimum charge', '', 'EA', 2300.00, NULL, NULL, false),
  ('pl-305', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Concrete Finisher - per hour', '', 'HR', 182.32, NULL, NULL, false),
  ('pl-306', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Concrete pump truck (per hour)', '', 'HR', 350.00, NULL, NULL, false),
  ('pl-307', 'Exterior Finish Ground Work/Pavers/Concrete/Gravel', 'Asphalt paving - 2" with 6" base - Residential', '', 'SF', 10.46, NULL, NULL, false),
  ('pl-308', 'Landscaping', 'Paver brick - High grade', '', 'SF', 16.86, NULL, NULL, false),
  ('pl-309', 'Landscaping', 'Block wall - decorative - retaining (Bid Item)', '', 'EA', 0, NULL, NULL, false),
  ('pl-310', 'Landscaping', 'Mulching (per CY)', '', 'CY', 74.49, NULL, NULL, false),
  ('pl-311', 'Landscaping', 'Mulching', '', 'SF', 0.65, NULL, NULL, false),
  ('pl-312', 'Fencing', 'Wood fence 5\', '', 'LF', 59.46, NULL, NULL, false),
  ('pl-313', 'Fencing', 'Basket weave fence - 4\', '', 'LF', 70.21, NULL, NULL, false),
  ('pl-314', 'Fencing', 'Basket weave fence gate - 4\', '', 'LF', 98.96, NULL, NULL, false),
  ('pl-315', 'Fencing', 'Basket weave fence gate - 2\', '', 'LF', 87.65, NULL, NULL, false),
  ('pl-316', 'Fencing', 'Vinyl (PVC) fence gate, 5\', '', 'LF', 228.64, NULL, NULL, false),
  ('pl-317', 'Fencing', 'Vinyl (PVC) fence gate, 3\', '', 'LF', 186.12, NULL, NULL, false),
  ('pl-318', 'Fencing', 'Stain - wood fence/gate', '', 'SF', 1.23, NULL, NULL, false),
  ('pl-319', 'Fencing', 'Seal & paint - wood fence/gate', '', 'SF', 1.62, NULL, NULL, false),
  ('pl-320', 'Fencing', 'Paint/finish - fence post - wood', '', 'EA', 26.49, NULL, NULL, false),
  ('pl-321', 'Fencing', 'Chain link fence w/posts & top rail - 4\', '', 'LF', 32.48, NULL, NULL, false),
  ('pl-322', 'Fencing', 'Chain link fence w/posts & top rail - 6\', '', 'LF', 40.22, NULL, NULL, false),
  ('pl-323', 'Fencing', 'Concrete post and panel fence - precast - 8\', '', 'LF', 121.73, NULL, NULL, false),
  ('pl-324', 'Fencing', 'Chain link fence gate - 6\', '', 'LF', 180.84, NULL, NULL, false),
  ('pl-325', 'Mitigation', 'Emergency service call', '', 'EA', 320.00, NULL, NULL, false),
  ('pl-326', 'Mitigation', 'General Demolition - per hour', '', 'HR', 80.22, NULL, NULL, false),
  ('pl-327', 'Mitigation', 'Water Extraction & Remediation Technician - per hour', '', 'HR', 101.42, NULL, NULL, false),
  ('pl-328', 'Mitigation', 'Air mover (per 24 hour period)', '', 'EA', 33.00, NULL, NULL, false),
  ('pl-329', 'Mitigation', 'Dehumidifier (per 24 hr period)', '', 'EA', 153.09, NULL, NULL, false),
  ('pl-330', 'Mitigation', 'Dust control barrier - tension post (per day)', '', 'DA', 3.35, NULL, NULL, false),
  ('pl-331', 'Dumpster', 'Dumpster load - Approx. 40 yards, 7-8 tons of debris', '', 'EA', 1950.00, NULL, NULL, false),
  ('pl-332', 'Dumpster', 'Dumpster load - Approx. 30 yards, 5-7 tons of debris', '', 'EA', 1570.00, NULL, NULL, false),
  ('pl-333', 'Dumpster', 'Haul debris - per pickup truck load - including dump fees', '', 'EA', 270.14, NULL, NULL, false),
  ('pl-334', 'Asphalt', 'Asphalt overlay - 1 1/2"', '', 'SF', 7.00, NULL, NULL, false),
  ('pl-335', 'Asphalt', 'Asphalt paving - 2" with 6" base - Residential', '', 'SF', 10.46, NULL, NULL, false),
  ('pl-336', 'Asphalt', 'Asphalt seal coat', '', 'SF', 0.85, NULL, NULL, false);

-- Add conflict handling for re-running the migration
-- If you need to re-run, use this instead:
-- ON CONFLICT (id) DO UPDATE SET
--   unit_price = EXCLUDED.unit_price,
--   labor_cost = EXCLUDED.labor_cost,
--   material_cost = EXCLUDED.material_cost;